call plug#begin()
Plug 'ctrlpvim/ctrlp.vim'
Plug 'majutsushi/tagbar'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
Plug 'git@github.com:yplaksyuk/vim-vebugger.git', { 'branch': 'develop' }
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'neoclide/jsonc.vim'
Plug 'digitaltoad/vim-jade'
Plug 'plasticboy/vim-markdown'
Plug 'tpope/vim-fugitive'
Plug 'morhetz/gruvbox'
call plug#end()

set encoding=utf-8
set nocompatible

syntax on
filetype plugin indent on

set number relativenumber numberwidth=5

set tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab

set completeopt=menu,preview
set complete-=i

set smartindent
set laststatus=2
set modelines=5
set hlsearch
set incsearch
set noswapfile nobackup

set path=**
set wildmenu
set wildmode=longest:full
set wildignore=*.swp,*/.git/*,*/docs/*,*/node_modules/*,*/dist/*

set list
set listchars=tab:→\ ,nbsp:␣,trail:•,eol:¶,precedes:«
set fillchars+=vert:\ 
"set colorcolumn=132
set cursorline

if has("patch-8.1.1564")
	set signcolumn=number
else
	set signcolumn=yes
endif

set nofoldenable


set background=dark

set wildcharm=<C-z>
nnoremap <esc><esc> :nohlsearch<cr>
"nnoremap <tab>   :b <C-z>
nnoremap <tab>   :CtrlPBuffer<cr>
nnoremap <S-tab> :b#<cr>
nnoremap <f6>   :cnext<cr>
nnoremap <f7>   :cprev<cr>
nnoremap <f9>   :VBGtoggleBreakpointThisLine<cr>
nnoremap <f10>  :VBGstepOver<cr>
nnoremap <f11>  :VBGstepIn<cr>
nnoremap <f12>  :VBGstepOut<cr>

nnoremap <leader>h :nohlsearch<cr>
nnoremap <leader>l :set list!<cr>
nnoremap <leader>w :only<cr>
nnoremap <leader>q :bd<cr>
nnoremap <leader>o :TagbarToggle<cr>
nnoremap <leader>d :LspDocumentDiagnostics<cr>
nnoremap <leader>p :LspDefinition<cr>
nnoremap <leader>? :LspHover<cr>


inoremap {<cr> {<cr>}<esc>O

source ~/.vim/filetype.vim
source ~/.vim/project.vim

"command! MakeTags !ctags -R include/ src/
let g:ctrlp_working_path_mode = 'rwa'
let g:ctrlp_match_window = 'max:30,results:100'

let g:vebugger_view_source_cmd='edit'

let g:vdebug_options = {
			\	'on_close': 'stop',
			\	'continuous_mode': 0,
			\	'layout': 'horizontal',
			\}

let g:lsp_highlight_references_enabled = 1

function! GitBranch()
	return system("git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n'")
endfunction

set statusline=[%n]\ %f%m%r%=%{GitBranch()}\ %{g:project_type}\ %l:%c\ %P\ [%{&fileformat}]

let s:vimrc=expand('<sfile>:p')

command! Vimrc execute 'edit ' . s:vimrc

autocmd vimenter * colorscheme gruvbox
